### PR TITLE
EAI JSON Converter

### PR DESCRIPTION
**Pull request by Jimjson**
eScript based EAI JSON Converter service to create and interpret JSON strings.

With this service one can convert ant property set into JSON string and vice versa.

Its not a best code but could help people to start with something.

### CODE REVIEW

**Comment by OracleSiebel** [comment]
Hi Jim,

Thanks for your contribution.

While I quickly test this out, could you move it under Example Code/EAI please.

It would be great if you can take an additional step to format the readme using Github's markdown format. This is about a two second job (just rename as .md) or you could go further and expose further details about how to use this. I'll probably do that at some point if you don't get around to it.

Finally, I also have another implementation of this same requirement from a colleague, but I think his code only went in one direction. I appreciate that JSON format can get quite complex, but that much integration will actually only need relatively simple structures.

It would be great to also have a full example of using this to interface to a REST endpoint somewhere out on the internet.

Anyway, for now, the only vital step is the directory re-alignment.

Thanks again for your effort.

**Comment by OracleSiebel** [comment]
Ideally the directory for this should be

ConfiguringSiebel\ExampleCode\EAI\JSONConvertor

**Comment by OracleSiebel** [comment]
Hi Jim,

Any reason to use this over and above your Java version ?

**Comment by Jimjson** [comment]
Hi there, Java based converter is no doubt more robust , but I have seen many people just give up on it because Java installation and integration with Siebel is difficult. Last thing you need with Siebel is more complexity. Happy to create another pull request for the Java based service if you recommend. Thanks, Jim

**Comment by OracleSiebel** [comment]
Yeh, I read some of the comments. I think a proper user guide and an Ant build file could help. In which case, let's have two subdirectories under the JSON Convertor folder, one for business service and one for Java. Then people can pick and choose.

**Comment by Jimjson** [comment]
Made those changes. Please check if it is ok.

**Pull request merged**
