### PR TITLE
Using Oracle Maps to display customer address in modal window 

### PR DESCRIPTION
**Pull request by carlosmlribeiro**
I've added this PR with details on how to add an Oracle Maps modal window from the customer form applet using colorbox plug in (http://www.jacklmoore.com/colorbox/)

### CODE REVIEW

**Comment by OracleSiebel** [comment]
Hi,

Thanks for your contribuition !

A couple of comments:

- Could you push this under the Open UI folder please? Perhaps even under a directory called Map Integration? I have a similar integration for Google Maps I could then place next to this one.
- As colorbox is a 3rd party library, I favour the idea of pushing this into a 3rdParty directory under custom. This would then provide a neat location for all 3rd Party libraries that custom PR/PMs reference, instead of pushing it all into one location. Your thoughts?
- Finally a readme.md would be great to explain where to obtain colorbox, and where to place it. You could take a couple of screen shots of manifest files and admin for this to round it off.

Let me know what you think. I'm happy to add this content.

Regards,

Duncan

**Comment by carlosmlribeiro** [comment]
Hi Duncan,

- Sure, it makes sense. I've actually started by Google Maps integration, but since Oracle Maps is shipped with Siebel and Google needs a license I've changed it for this one. I've pulled it here because I found it nothing similar online and it took me a while to find how to use the Oracle methods
- Yes, 100% agree. I have that in Production but not the same "neat" organization in my sandbox.
- Will do, on Monday ;-)

Regards,

Carlos

**Comment by carlosmlribeiro** [comment]
Hi,

I've added more information about this integration. Please let me know your thoughts.

Regards,

Carlos

**Comment by OracleSiebel** [comment]
Hi Carlos,

Thanks for the updates. This now sits nicely within the repository so I've merged this. It can be maintained from here. Readme content is a great start. One remark; it might be nice if the readme also shows the end result.

Thanks again !

Duncan

**Comment by OracleSiebel** [comment]
Hi Carlos,

I've just applied some changes to the Oracle Map integration. I'll apply these to the master repo in a few days, but wanted to give you a chance to comment on them before I do so.

https://github.com/OracleSiebel/ConfiguringSiebel/tree/Oracle-Map-Integration-Tidying/ExampleCode/Open%20UI/Maps%20Integration/OracleMaps

Please let me have any feedback.

**Comment by carlosmlribeiro** [comment]
Hi,

Sorry, I've just now saw the changes.It looks good, the testing chapter in the Readme is a good standard. The indentation was lost on the PR, not sure if you want to correct it.

Thanks for tyding that up for me and have a nice weekend!

Carlos

**Comment by OracleSiebel** [comment]
Tidied. Thanks for spotting that.

**Pull request merged**
